### ISSUE TITLE
While searching for double channel 3D image agumentation, I would like to inquire.

### ISSUE THREAD

**Issue by SangWoonJeong** [quartermaine/quartermaine#1]
Hello.

I will contact you after looking for double channel 3D image agumentation.

I am also looking for the same image agumentation code.

Has this been solved?

If this is resolved, I would like to ask for help.

Thank you.

Confirmed,
https://github.com/tensorflow/tensorflow/issues/43145#issue-699233077
https://github.com/tanzhenyu/image_augmentation/issues/2

**Comment by quartermaine** [comment]
Hello,

Yes, I tried two methods on tensorflow, one with constructing augmented TfRecords and the other on the fly using tf.function.
From my experience the augmentation on the fly is very slow on training and needs a lot time and epochs/steps, regarding the already augmented TfRecords I used numpy.

/Andreas

**Comment by SangWoonJeong** [comment]
Thank you for answer.

Then, can you find github referring to 2channel augmnetation code using numpy?

/SangwoonJeong

**Comment by quartermaine** [comment]
Yes, have a look at this one [repo](https://github.com/mdciri/Vox2Vox)
I plan to upload my code after finishing my project.

**Comment by SangWoonJeong** [comment]
Thank you very much.
I will also refer to your github later.

**Comment by quartermaine** [comment]
Thank you.
Good luck!
